### ISSUE TITLE
without proper permissions '0o41777' set.

### ISSUE THREAD

**Issue by mthang** [qiime2/galaxy-tools#62]
Can you please advise what can I do to fix the issue on Galaxy ? We keep running into this situation and expect to see more of this issues in the future.

**Unexpected error loading arguments in
q2galaxy: Directory '/tmp/qiime2'
already exists without proper
permissions '0o41777' set. Current
permissions are '0o40777.' This most
likely means something other than
QIIME 2 created the directory
'/tmp/qiime2' or QIIME 2 failed
between creating '/tmp/qiime2' and
setting permissions on it.**

**Comment by gregcaporaso** [comment]
Hi @mthang, We provide this type of support on the [QIIME 2 Forum](https://forum.qiime2.org). Could you post this question there? Thank you!
