### ISSUE TITLE
More specific stdio parsing

### ISSUE THREAD

**Issue by bernt-matthias** [qiime2/galaxy-tools#63]
We got a report that dada2 crashed on some instance with the following in the stderr

```
raise Exception("An error was encountered while running DADA2"
Exception: An error was encountered while running DADA2 in R (return code -9), please inspect stdout and stderr to learn more.
```

the forums seem to suggest that this may indicate an out of memory (OOM) -- I did not check.

Depending of the job runner that is used this may be detected automatically by Galaxy, e.g. if SLURM is used. 

But also the Galaxy could be annotated to help with detecting such cases: https://docs.galaxyproject.org/en/master/dev/schema.html#tool-stdio

Was wondering if we can accomodate for this by maintainging (manually curated) macro(s) that we can include in the autogenerated tools.

**Comment by ebolyen** [comment]
Would the goal be to report the OOM to the job executor for re-running? Or is there a better way to report OOM to the user based on the job executor?

**Comment by bernt-matthias** [comment]
> Would the goal be to report the OOM to the job executor for re-running? 

Yes. Rerunning can even be triggered automatically if the Galaxy admin has configured a job resubmission schema. 

> Or is there a better way to report OOM to the user based on the job executor?

I don't think so. The user will see the message if no resubmission is configured. Then the user has to ask the admin for more memory for the corresponding tool.

**Comment by Oddant1** [comment]
@ebolyen, parsl has some mechanism for keeping track of the status of its tasks, and it also has a built-in retry system, but I think it's a bit more naive than galaxy's (I believe it just tries the exact same thing again and hopes whatever went wrong last time doesn't this time)
